services:
  - type: web
    name: norsu-alumni
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py seed_cms_data
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: norsu_alumni.settings
    healthCheckPath: /
    autoDeploy: true